# -*- coding: utf-8 -*-
"""Flight Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QWuzncvbDmI7loiLUnHhclpJLv_J2auG

### Accessing Google Sheets from Drive

To access Google Sheets from your Drive in Colab, you'll typically need to:
1.  Install the `gspread` library.
2.  Authenticate your Google account to grant necessary permissions.
3.  Use the sheet's URL to open it and read its data.
"""

# Install gspread library
!pip install gspread

import pandas as pd
import seaborn as sns
import gspread
from google.colab import auth
import google.auth

# Authenticate with Google Colab
auth.authenticate_user()

# Get user credentials and authorize gspread to access your Google Sheets
credentials, project_id = google.auth.default()
gc = gspread.authorize(credentials)

"""# New Section
Load the dataset into the project and display the columns information
"""

data = pd.read_csv('/content/big_mart_sales.csv')
print(data)

"""Check which columns have missing values"""

data.isna().sum()

"""Get the shape of the data"""

print(data.shape)

"""Display the data types of all the columns"""

print(data.dtypes)

"""Get the info regarding all the tables"""

print(data.info())

"""# **Data** **Visualization**

import matplotlib
"""

import matplotlib.pyplot as plt

"""Use matplotlib to display a graph that shows the relationship between the item_type and item_outlet_sales"""

x=data['Item_Type']
y=data['Item_Outlet_Sales']
plt.bar(x,y)
plt.xlabel('Item_Type')
plt.ylabel('Item_Outlet_Sales')
plt.title('Item_Type vs Item_Outlet_Sales')
plt.xticks(rotation=90)
plt.show()

"""Determine if fat content affects sales"""

import pandas as pd

data = pd.read_csv('/content/big_mart_sales.csv')
x = data['Item_Fat_Content']
y = data['Item_Outlet_Sales']
plt.bar(x,y)
plt.xlabel('Item_Fat_Content')
plt.ylabel('Item_Outlet_Sales')
plt.title('Item_Fat_Content vs Item_Outlet_Sales')
#plt.xticks(rotation=90)
plt.show()

"""Display a graph about outlet_sales and the frequency"""

sns.histplot(data['Item_Outlet_Sales'], bins=30, kde=True)
plt.title('Distribution of Item Outlet Sales')
plt.xlabel('Item Outlet Sales')
plt.ylabel('Frequency')
plt.show()

"""Determine the relationship between outlet_sales and outlet_type"""

x= data['Outlet_Type']
y= data['Item_Outlet_Sales']
plt.bar(x,y)
plt.xlabel('Outlet_Type')
plt.ylabel('Item_Outlet_Sales')
plt.title('Outlet_Type vs Item_Outlet_Sales')
plt.xticks(rotation=90)
plt.show()

"""Determine if item_visibility affects its sales"""

sns.scatterplot(data=data, x='Item_Visibility', y='Item_Outlet_Sales')
plt.xlabel('Item_Visibility')
plt.ylabel('Item_Outlet_Sales')
plt.title('Item_Visibility vs Item_Outlet_Sales')
plt.show

"""Which item types have the highest sales value"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Load the dataset

#Group the data firstly according to the item_type, then calculate the mean usung the item_outlet_sales
data = pd.read_csv('/content/big_mart_sales.csv')
avg_sales = data.groupby('Item_Type')['Item_Outlet_Sales'].mean()
avg_sales.sort_values(ascending=False, inplace=True)
sns.barplot(x=avg_sales.index, y=avg_sales)
plt.xlabel('Item_Type')
plt.ylabel('Average_Sales')
plt.title('Item_Type vs Average_Sales')
plt.xticks(rotation=90)
plt.show

"""Determine if outlet type has an impact on the sales eg what do most people buy at a grocery store outlet."""

x= data['Outlet_Type']
y = data['Item_Outlet_Sales']
plt.bar(x,y)
plt.xticks(rotation = 45)
plt.ylabel('Outlet type')
plt.ylabel('Item outlet sales')
plt.show()

"""Do older outlets have different different sales compared to newer ones"""

year_sales = data.groupby('Outlet_Establishment_Year')['Item_Outlet_Sales'].mean()
sns.barplot(x=year_sales.index, y=year_sales)
plt.xlabel('Outlet_Establishment_Year')
plt.ylabel('Average_Sales')
plt.title('Outlet_Establishment_Year vs Average_Sales')
plt.show()

"""Create a correlation to better understand the relatioship between the columns.

"""

correlation = data.corr(numeric_only=True)
print(correlation)

"""Create a heatMap that displays the correlation created"""

sns.heatmap(correlation, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

"""Create and display a boxplot for Item_outlet_sales"""

sns.boxplot(data=data, x='Item_Type', y='Item_Outlet_Sales')
plt.xlabel('Item_Type')
plt.ylabel('Item_Outlet_Sales')
plt.title('Item_Type vs Item_Outlet_Sales')
plt.xticks(rotation=90)
plt.show()

"""Find the missing values"""

data.isna().sum()

"""Create a cros tabulation between Outlet_Type and Outlet_size th further investigate the pattern of the missing values"""

pd.crosstab(data['Outlet_Type'], data['Outlet_Size'])

pd.crosstab(data['Outlet_Type'], data['Outlet_Size'])

"""### Handling Missing Values

From the `data.isna().sum()` output, we can see missing values in 'Item_Weight' and 'Outlet_Size'. We'll impute 'Item_Weight' with the mean and 'Outlet_Size' with the mode, as it's a categorical feature.

### Descriptive Statistics

Let's look at the basic descriptive statistics for the numerical columns to get an overview of the data distribution.
"""

# Display descriptive statistics for numerical columns
display(data.describe())

"""### Data Visualization

Now, let's create some visualizations to understand the distributions and relationships within the data.

First, a histogram of 'Item_Outlet_Sales' to see its distribution.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set the style for seaborn plots
sns.set_style("whitegrid")

plt.figure(figsize=(10, 6))
sns.histplot(data['Item_Outlet_Sales'], bins=30, kde=True)
plt.title('Distribution of Item Outlet Sales')
plt.xlabel('Item Outlet Sales')
plt.ylabel('Frequency')
plt.show()

"""Next, let's visualize the distribution of sales across different 'Outlet_Type' categories using a box plot."""

plt.figure(figsize=(12, 7))
sns.boxplot(x='Outlet_Type', y='Item_Outlet_Sales', data=data)
plt.title('Item Outlet Sales by Outlet Type')
plt.xlabel('Outlet Type')
plt.ylabel('Item Outlet Sales')
plt.xticks(rotation=45)
plt.show()

"""Let's also look at the impact of 'Item_Fat_Content' on 'Item_Outlet_Sales'."""

plt.figure(figsize=(10, 6))
sns.boxplot(x='Item_Fat_Content', y='Item_Outlet_Sales', data=data)
plt.title('Item Outlet Sales by Item Fat Content')
plt.xlabel('Item Fat Content')
plt.ylabel('Item Outlet Sales')
plt.show()

"""### Cleaning 'Item_Fat_Content'

We noticed inconsistent spellings in 'Item_Fat_Content' ('Low Fat', 'low fat', 'LF', 'Regular', 'reg'). Let's standardize these to 'Low Fat' and 'Regular' for better analysis.
"""

# Standardize 'Item_Fat_Content' values
data['Item_Fat_Content'] = data['Item_Fat_Content'].replace({
    'low fat': 'Low Fat',
    'LF': 'Low Fat',
    'reg': 'Regular'
})

print("Unique values in 'Item_Fat_Content' after cleaning:")
display(data['Item_Fat_Content'].value_counts())

"""### Analyzing Sales by Outlet Location Type

Let's visualize the relationship between 'Outlet_Location_Type' and 'Item_Outlet_Sales' to see if geographical location impacts sales.
"""

plt.figure(figsize=(10, 6))
sns.boxplot(x='Outlet_Location_Type', y='Item_Outlet_Sales', data=data)
plt.title('Item Outlet Sales by Outlet Location Type')
plt.xlabel('Outlet Location Type')
plt.ylabel('Item Outlet Sales')
plt.show()

"""### Exploring Item Type vs. Sales

Finally, let's look at the distribution of 'Item_Outlet_Sales' across different 'Item_Type' categories. Since there are many item types, we might want to aggregate or focus on the top ones.
"""

plt.figure(figsize=(14, 7))
sns.boxplot(x='Item_Type', y='Item_Outlet_Sales', data=data)
plt.title('Item Outlet Sales by Item Type')
plt.xlabel('Item Type')
plt.ylabel('Item Outlet Sales')
plt.xticks(rotation=90)
plt.show()

"""### Correlation Analysis

Let's analyze the correlation between numerical features to identify strong relationships that might be useful for modeling or further insights.
"""

# Select only numerical columns for correlation calculation
numerical_data = data.select_dtypes(include=['number'])

# Calculate the correlation matrix
correlation_matrix = numerical_data.corr()

# Plot the heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix of Numerical Features')
plt.show()

"""### Correlation Analysis

Let's analyze the correlation between numerical features to identify strong relationships that might be useful for modeling or further insights.
"""

# Select only numerical columns for correlation calculation
numerical_data = data.select_dtypes(include=['number'])

# Calculate the correlation matrix
correlation_matrix = numerical_data.corr()

# Plot the heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix of Numerical Features')
plt.show()